repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Use the latest stable version
    hooks:
      - id: trailing-whitespace
        description: Remove trailing whitespace.
      - id: end-of-file-fixer
        description: Ensure a single newline at the end of files.
      - id: check-added-large-files
        args: ["--maxkb=500"] # Warn if files larger than 500 KB are added.

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1 # Use the latest stable version
    hooks:
      - id: flake8
        args:
          - "--max-line-length=120" # Adjusted based on my style guide
          - "--ignore=D202" # Ignore the D202 error related to docstring
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-docstrings

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args:
          - "--strict" # Enable strict type checking
          - "--explicit-package-bases"
          - "--exclude=^ftptomongo/__main__.py$"
        always_run: true # Run on every commit, even if no staged files
        files: \.(py)$ # This will match all Python files

  #  - repo: https://github.com/conventional-changelog/commitlint
  #    rev: v17.0.0  # Or any stable version
  - repo: local
    hooks:
      - id: commitlint
        name: commitlint
        entry: npx --no-install commitlint --edit .git/COMMIT_EDITMSG
        language: node
        stages: [commit-msg]
        pass_filenames: false

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: ["--line-length=120"]

  #  - repo: https://github.com/pre-commit/mirrors-pylint
  #    rev: v2.7.4
  #    hooks:
  #      - id: pylint
  #        args:
  #          - "--output-format=colorized"
  #          - "disable=raw-checker-failed,
  #            bad-inline-option,
  #            locally-disabled,
  #            file-ignored,
  #            suppressed-message,
  #            useless-suppression,
  #            deprecated-pragma,
  #            use-symbolic-message-instead,
  #            E1101"
  #          - "--rcfile=.pylintrc"
  #        files: ^(\./)?(tests/.*\.py|[^/]*\.py)$ # Only scan these directories
  #        exclude: ^\.cache # Exclude .cache folder from being scanned
  #        fail_fast: true # Do not block commits based on errors

  #  working but not ready to fix it yet as use it for testng purposes
  #  - repo: https://github.com/PyCQA/bandit
  #    rev: 1.8.0
  #    hooks:
  #      - id: bandit
  #        args:
  #          - "--config=.bandit.yml"
  #        files: ^(face_detection|image_processor)/.*\.py$ # This matches the current directory and the image_processing directory
  #        fail_fast: false # Do not block commits based on errors

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        description: Validate YAML files.

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: ["--write"]
        files: \.(json|md|yml|yaml)$
