#build and image
name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      #- name: Build Docker Image
      #  run: |
      #    docker buildx create --use
      #    docker buildx build \
      #      --tag ftptomongo:latest \
      #      --file Dockerfile \
      #      .

      - name: Find and Update Version
        id: find-version
        run: |
          echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
           
          # Find the existing version label, if it exists
          existing_version_label=$(docker inspect --format '{{ index .Config.Labels "version" }}' ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest)
          #echo "existing_version_label: $existing_version_label"

          # If the existing version label is not empty, increase it by 0.01; otherwise, set it to 0.01
          if [ -n "$existing_version_label" ]; then
            new_version=$(echo "$existing_version_label + 0.01" | bc)
            # Format the new version to have two decimal places
            new_version=$(printf "%.2f" $new_version)
          else
            new_version="0.01"
            existing_version_label="0.00"
          fi

          # Output the new version
          echo "new_version:$new_version"
          echo "existing_version:$existing_version_label"
          echo "new_version=$new_version" >> $GITHUB_ENV
          echo "existing_version=$existing_version" >> $GITHUB_ENV

        
        continue-on-error: true
    
      - name: Build Docker Image
        run: |
          echo "start creating a docker image"
          docker buildx create --use
          echo "start building a docker image"
          docker buildx build \
            --label version=$new_version \
            --file Dockerfile \
            -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest \
            .

      - name: Build and Push Docker Image
        run: |
          echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest