name: ci:publish docker image
on:
    push:
      branches:
        - main
    workflow_dispatch:
        
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            docker.io/${{ github.repository }}
            ghcr.io/${{ github.repository }}
            quay.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=true
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHA_TOKEN }}
      - name: Login to Red Hat Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Debug secrets
        run: |
          echo "FTP_USER: ${{ secrets.FTP_USER }}"
          echo "FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}"
          echo "MONGO_HOST: ${{ secrets.MONGO_HOST }}"
          echo "FTP_PORT: ${{ secrets.FTP_PORT }}"
        env:
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          FTP_PORT: ${{ secrets.FTP_PORT }}
      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          FTP_PORT: ${{ secrets.FTP_PORT }}
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            "SECRET_FTP_USER = ${{ secrets.FTP_USER }}"
            "SECRET_FTP_PASS = ${{ secrets.FTP_PASSWORD }}"
            "SECRET_MONGO_HOST = ${{ secrets.MONGO_HOST }}"
            "SECRET_FTP_PORT_GHA = ${{ secrets.FTP_PORT }}"
          build-args: |
            SECRET_FTP_USER=${{ secrets.FTP_USER }}
            SECRET_FTP_PASS=${{ secrets.FTP_PASSWORD }}
            SECRET_MONGO_HOST=${{ secrets.MONGO_HOST }}
            SECRET_FTP_PORT=${{ secrets.FTP_PORT }}
      
       
            