name: Deploy to Google Cloud

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Upload Python Package"] 
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: '343.0.0'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          PROJECT_ID: smooth-verve-400915

      #- name: Check if Google Cloud project exists
      #  run: |
      #    gcloud projects describe $PROJECT_ID || terraform apply -var="project_id=$PROJECT_ID" -var="location=europe-west1" -var="zone=europe-west1-b" -var="machine_type=g1-small" path/to/terraform/directory
      #  continue-on-error: true

      - name: Configure Docker
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      #- name: Install Docker Compose
      #  run: |
      #    pip install docker-compose
      #    docker-compose --version

      - name: Install gcloud
        run: |
          gcloud components install
          gcloud components update


      - name: Deploy latest image
        run: |
          # Pull the latest image from GHCR.io
          echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker pull ghcr.io/nill2/ftptomongo:latest

          gcloud run deploy ftptomongo-cluster \
            --image ghcr.io/nill2/ftptomongo:latest \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated
