name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix: 
        version: [1]

    steps:
      - name: defauld directory
        run: |
          echo "CurrentDirectory=$(pwd)" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v2
  
      - name: Install Miniconda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-py38_4.9.2-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          source "$HOME/miniconda/etc/profile.d/conda.sh"
          conda activate base
          conda config --set always_yes yes --set changeps1 no
          conda update -q conda
          conda env update --file environment.yml --name base
        env:
          CONDA_HOME: $HOME/miniconda
 

    #  - uses: actions/checkout@v3
    #  - name: Update Conda
    #    run: |
    #      conda update conda -y

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install pyftpdlib from PyPI
        run: |
          pip install pyftpdlib
     # - name: Install dependencies
     #   run: |
     #     cd "$current_directory"
     #     echo "$GITHUB_PATH"
     #     echo "$(pwd)"
     #     echo "$ls"
     #     conda env update --file environment.yml --name base
     #     conda install -c conda-forge pyftpdlib  # Install pyftpdlib
      - name: Lint with flake8
        run: |
          cd "$CurrentDirectory"
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Install pymongo
        run: |
          pip install pymongo
      - name: Test with pytest
        run: |
          cd "$CurrentDirectory" 
          conda install pytest
          pytest 
